# Generated by Django 3.1.2 on 2020-11-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dep_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=255, verbose_name='科室名字')),
                ('dep_type', models.IntegerField()),
            ],
            options={
                'verbose_name': '科室分类',
                'db_table': 'department_info',
            },
        ),
        migrations.CreateModel(
            name='HInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htitle', models.CharField(max_length=255, verbose_name='医院名称')),
                ('htime', models.CharField(max_length=255, verbose_name='预约放号时间')),
                ('hgrade', models.CharField(max_length=255, verbose_name='医院等级')),
                ('himg', models.CharField(max_length=255, verbose_name='医院图片')),
                ('hlocal', models.CharField(max_length=255, verbose_name='医院所属地')),
            ],
            options={
                'verbose_name': '医院信息',
                'db_table': 'hospital_info',
            },
        ),
        migrations.CreateModel(
            name='Dep_Detail_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_detail_title', models.CharField(max_length=10, verbose_name='科目详细名字')),
                ('dep_detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msisystem.dep_info', verbose_name='科目对应科室')),
            ],
            options={
                'verbose_name': '科目分类',
                'db_table': 'department_detail_Info',
            },
        ),
    ]
