# Generated by Django 3.1.2 on 2020-11-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msisystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htitle', models.CharField(max_length=255, verbose_name='医院名称')),
                ('himg', models.CharField(max_length=255, verbose_name='医院图片')),
                ('hlocal', models.CharField(max_length=255, verbose_name='医院所属地')),
                ('hclinicstr_covid', models.CharField(max_length=255, verbose_name='医院所属地')),
            ],
            options={
                'verbose_name': '科目分类',
                'db_table': 'department_clinic_Info',
            },
        ),
    ]
